name: deployToCloud

on:
  schedule:
    - cron: '0 7 * * 1,3,5'
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: 'checkout upstream'
      uses: actions/checkout@v2
      with:
        ref: master
    - name: 'set up git'
      run: |
        git config pull.rebase true
        git remote add upstream https://github.com/DIYgod/RSSHub/
        git config user.name ${{ secrets.GIT_USER }}
        git config user.email ${{ secrets.GIT_EMAIL }}
        git reset --hard upstream/master
        git pull upstream master
    - name: 'write yaml'
      run: |
        touch app.yaml
        echo "${{secrets.APP_YAML}}" >> app.yaml
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Deploy to App Engine'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: 'app.yaml'
        promote: false
        version: 'v1'