name: deployToCloud

on:
  schedule:
    - cron: '0 7 1,15 * *'
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: 'checkout upstream'
      uses: actions/checkout@v2
      with:
        name: DIYgod/RSSHub
        ref: master
    - name: 'write yaml'
      run: |
        touch app.yaml
        echo "${{secrets.APP_YAML}}" >> app.yaml
    - name: auth
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Deploy to App Engine'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: 'app.yaml'
        promote: false
        version: 'v1'
